server:
  port: 8080

spring:
  application:
    name: api-gateway
  config:
    import:
    - optional:file:/common-config/application-actuator.yaml
    - optional:file:/common-config/application-devtools.yml
    - optional:file:/common-config/application-openapi.yml
    - optional:file:/common-config/application-resilience4j.yml



  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Автоматическое создание роутов через discovery
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service  # ← ЯВНО с балансировкой!
          predicates:
            - Path=/api/users/**
          filters:
            - name: JwtAuthenticationFilter
            - name: CircuitBreaker
              args:
                name: userServiceGateway
                fallbackUri: forward:/fallback/users

        - id: task-service
          uri: lb://task-service  # ← ЯВНО с балансировкой!
          predicates:
            - Path=/api/tasks/**
          filters:
            - name: JwtAuthenticationFilter
            - name: CircuitBreaker
              args:
                name: taskServiceGateway
                fallbackUri: forward:/fallback/tasks

        - id: public-auth
          uri: lb://user-service  # ← ТОЖЕ С БАЛАНСИРОВКОЙ!
          predicates:
            - Path=/api/auth/register, /api/auth/login
          filters:
            - RewritePath=/api/auth/(?<path>.*), /api/users/$\{path}

        - id: user-service-openapi
          uri: lb://user-service
          predicates:
            - Path=/v3/api-docs/user-service
          filters:
            - RewritePath=/v3/api-docs/user-service, /api-docs

        - id: task-service-openapi
          uri: lb://task-service
          predicates:
            - Path=/v3/api-docs/task-service
          filters:
            - RewritePath=/v3/api-docs/task-service, /api-docs

        - id: analytics-service-openapi
          uri: lb://analytics-service
          predicates:
            - Path=/v3/api-docs/analytics-service
          filters:
            - RewritePath=/v3/api-docs/analytics-service, /api-docs
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true



eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/  # ← АДРЕС EUREKA
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${random.value}
    hostname: ${spring.application.name}
    prefer-ip-address: false # Регистрироваться по IP, а не по hostname
    lease-renewal-interval-in-seconds: 30  # Частота отправки heartbeats
    lease-expiration-duration-in-seconds: 90  # Через сколько удалить, если нет heartbeats


logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.todo.gateway: DEBUG
    reactor.netty: DEBUG