server:
  port: 8082

spring:
  application:
    name: task-service
  config:
    import:
      - optional:file:/common-config/application-devtools.yml
      - optional:file:/common-config/application-actuator.yaml
      - optional:file:/common-config/application-openapi.yml



  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      # Сериализаторы (превращают объекты в байты)
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

      # Настройки надежности
      retries: 3                    # Повторить 3 раза при ошибке
      acks: all                     # Ждать подтверждения от всех реплик

      # Настройки производительности
      batch-size: 16384             # 16 KB - размер батча
      linger-ms: 5                   # Ждать 5 мс перед отправкой
      buffer-memory: 33554432        # 32 MB - буфер памяти

      # Сжатие (экономит трафик)
      compression-type: snappy

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/  # ← АДРЕС EUREKA
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${random.value}
    hostname: ${spring.application.name}
    prefer-ip-address: false  # Регистрироваться по IP, а не по hostname
    lease-renewal-interval-in-seconds: 30  # Частота отправки heartbeats
    lease-expiration-duration-in-seconds: 90  # Через сколько удалить, если нет heartbeats
logging:
  level:
    org.springframework.security: DEBUG      # Логи безопасности (почему 403)
    com.todo.task.config: DEBUG              # Ваши фильтры и конфигурация
    org.springframework.web: DEBUG